In [99]:
import numpy as np
import re
import pandas as pd
df=pd.read_csv('Weather_chennai_1.csv',delimiter=',')

In [100]:
data=pd.DataFrame(df)

In [101]:
df

,Unnamed: 0,date,date_id,wind,desc,temp,baro,hum
0,0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9,Drizzle. Fog.,30.0,1003,82
1,1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14,Fog.,29.0,1002,80
2,2,"Monday 15 July 2024, 06.00 — 12.00",1.721023e+12,17,Drizzle. Broken clouds.,29.0,1003,82
3,3,"Monday 15 July 2024, 12.00 — 18.00",1.721045e+12,13,Drizzle. Broken clouds.,29.0,1001,85
4,4,"Monday 15 July 2024, 18.00 — 00.00",1.721066e+12,19,Fog.,29.0,1002,84
...,...,...,...,...,...,...,...,...
1063,1063,"Saturday 30 January 2010, 18.00 — 00.00",1.264874e+12,10,Passing clouds.,26.0,1016,76
1064,1064,"Sunday 31 January 2010, 00.00 — 06.00",1.264896e+12,0,Clear.,23.0,1015,91
1065,1065,"Sunday 31 January 2010, 06.00 — 12.00",1.264918e+12,7,Haze.,29.0,1017,75
1066,1066,"Sunday 31 January 2010, 12.00 — 18.00",1.264939e+12,16,Passing clouds.,29.0,1014,55
1067,1067,"Sunday 31 January 2010, 18.00 — 00.00",1.264961e+12,7,Passing clouds.,26.0,1016,76

In [102]:
df[['day', 'time_range']] = df['date'].str.split(',', expand=True)
df['time_range'] = df['time_range'].str.strip()

In [103]:
df

,Unnamed: 0,date,date_id,wind,desc,temp,baro,hum,day,time_range
0,0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9,Drizzle. Fog.,30.0,1003,82,Sunday 14 July 2024,18.00 — 00.00
1,1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14,Fog.,29.0,1002,80,Monday 15 July 2024,00.00 — 06.00
2,2,"Monday 15 July 2024, 06.00 — 12.00",1.721023e+12,17,Drizzle. Broken clouds.,29.0,1003,82,Monday 15 July 2024,06.00 — 12.00
3,3,"Monday 15 July 2024, 12.00 — 18.00",1.721045e+12,13,Drizzle. Broken clouds.,29.0,1001,85,Monday 15 July 2024,12.00 — 18.00
4,4,"Monday 15 July 2024, 18.00 — 00.00",1.721066e+12,19,Fog.,29.0,1002,84,Monday 15 July 2024,18.00 — 00.00
...,...,...,...,...,...,...,...,...,...,...
1063,1063,"Saturday 30 January 2010, 18.00 — 00.00",1.264874e+12,10,Passing clouds.,26.0,1016,76,Saturday 30 January 2010,18.00 — 00.00
1064,1064,"Sunday 31 January 2010, 00.00 — 06.00",1.264896e+12,0,Clear.,23.0,1015,91,Sunday 31 January 2010,00.00 — 06.00
1065,1065,"Sunday 31 January 2010, 06.00 — 12.00",1.264918e+12,7,Haze.,29.0,1017,75,Sunday 31 January 2010,06.00 — 12.00
1066,1066,"Sunday 31 January 2010, 12.00 — 18.00",1.264939e+12,16,Passing clouds.,29.0,1014,55,Sunday 31 January 2010,12.00 — 18.00
1067,1067,"Sunday 31 January 2010, 18.00 — 00.00",1.264961e+12,7,Passing clouds.,26.0,1016,76,Sunday 31 January 2010,18.00 — 00.00

In [104]:
df['day'] = pd.to_datetime(df['day'], format='%A %d %B %Y')
df['month'] = df['day'].dt.month

In [105]:
df['day_date']=df['day'].dt.day

In [106]:
df['year']=df['day'].dt.year
df['day_name']=df['day'].dt.day_name()

In [107]:
df.head()

,Unnamed: 0,date,date_id,wind,desc,temp,baro,hum,day,time_range,month,day_date,year,day_name
0,0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9,Drizzle. Fog.,30.0,1003,82,2024-07-14,18.00 — 00.00,7,14,2024,Sunday
1,1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14,Fog.,29.0,1002,80,2024-07-15,00.00 — 06.00,7,15,2024,Monday
2,2,"Monday 15 July 2024, 06.00 — 12.00",1.721023e+12,17,Drizzle. Broken clouds.,29.0,1003,82,2024-07-15,06.00 — 12.00,7,15,2024,Monday
3,3,"Monday 15 July 2024, 12.00 — 18.00",1.721045e+12,13,Drizzle. Broken clouds.,29.0,1001,85,2024-07-15,12.00 — 18.00,7,15,2024,Monday
4,4,"Monday 15 July 2024, 18.00 — 00.00",1.721066e+12,19,Fog.,29.0,1002,84,2024-07-15,18.00 — 00.00,7,15,2024,Monday

In [108]:
df[['Start_hour', 'End_hour']] = df['time_range'].str.split('—', expand=True)

df['Start_hour'] = df['Start_hour'].str.strip()
df['End_hour'] = df['End_hour'].str.strip()

In [109]:
df

,Unnamed: 0,date,date_id,wind,desc,temp,baro,hum,day,time_range,month,day_date,year,day_name,Start_hour,End_hour
0,0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9,Drizzle. Fog.,30.0,1003,82,2024-07-14,18.00 — 00.00,7,14,2024,Sunday,18.00,00.00
1,1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14,Fog.,29.0,1002,80,2024-07-15,00.00 — 06.00,7,15,2024,Monday,00.00,06.00
2,2,"Monday 15 July 2024, 06.00 — 12.00",1.721023e+12,17,Drizzle. Broken clouds.,29.0,1003,82,2024-07-15,06.00 — 12.00,7,15,2024,Monday,06.00,12.00
3,3,"Monday 15 July 2024, 12.00 — 18.00",1.721045e+12,13,Drizzle. Broken clouds.,29.0,1001,85,2024-07-15,12.00 — 18.00,7,15,2024,Monday,12.00,18.00
4,4,"Monday 15 July 2024, 18.00 — 00.00",1.721066e+12,19,Fog.,29.0,1002,84,2024-07-15,18.00 — 00.00,7,15,2024,Monday,18.00,00.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,1063,"Saturday 30 January 2010, 18.00 — 00.00",1.264874e+12,10,Passing clouds.,26.0,1016,76,2010-01-30,18.00 — 00.00,1,30,2010,Saturday,18.00,00.00
1064,1064,"Sunday 31 January 2010, 00.00 — 06.00",1.264896e+12,0,Clear.,23.0,1015,91,2010-01-31,00.00 — 06.00,1,31,2010,Sunday,00.00,06.00
1065,1065,"Sunday 31 January 2010, 06.00 — 12.00",1.264918e+12,7,Haze.,29.0,1017,75,2010-01-31,06.00 — 12.00,1,31,2010,Sunday,06.00,12.00
1066,1066,"Sunday 31 January 2010, 12.00 — 18.00",1.264939e+12,16,Passing clouds.,29.0,1014,55,2010-01-31,12.00 — 18.00,1,31,2010,Sunday,12.00,18.00
1067,1067,"Sunday 31 January 2010, 18.00 — 00.00",1.264961e+12,7,Passing clouds.,26.0,1016,76,2010-01-31,18.00 — 00.00,1,31,2010,Sunday,18.00,00.00

In [110]:
df=df.drop(('time_range'),axis=1)

In [111]:
df.columns

Index(['Unnamed: 0', 'date', 'date_id', 'wind', 'desc', 'temp', 'baro', 'hum',
       'day', 'month', 'day_date', 'year', 'day_name', 'Start_hour',
       'End_hour'],
      dtype='object')

In [112]:
df=df[['date', 'date_id', 'wind', 'desc', 'temp', 'baro', 'hum',
       'day', 'month', 'day_date', 'year','day_name', 'Start_hour', 'End_hour']]

In [113]:
df[['wind','temp','baro']]=df[['wind','temp','baro']].astype(float)
df[['hum','year','day_date']]=df[['hum','year','day_date']].astype(int)

In [114]:
from datetime import datetime
df['Start_hour'] = pd.to_datetime(df['Start_hour'], format='%H.%M').dt.strftime('%H:%M')
df['End_hour'] = pd.to_datetime(df['End_hour'], format='%H.%M').dt.strftime('%H:%M')

In [115]:
df

,date,date_id,wind,desc,temp,baro,hum,day,month,day_date,year,day_name,Start_hour,End_hour
0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9.0,Drizzle. Fog.,30.0,1003.0,82,2024-07-14,7,14,2024,Sunday,18:00,00:00
1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14.0,Fog.,29.0,1002.0,80,2024-07-15,7,15,2024,Monday,00:00,06:00
2,"Monday 15 July 2024, 06.00 — 12.00",1.721023e+12,17.0,Drizzle. Broken clouds.,29.0,1003.0,82,2024-07-15,7,15,2024,Monday,06:00,12:00
3,"Monday 15 July 2024, 12.00 — 18.00",1.721045e+12,13.0,Drizzle. Broken clouds.,29.0,1001.0,85,2024-07-15,7,15,2024,Monday,12:00,18:00
4,"Monday 15 July 2024, 18.00 — 00.00",1.721066e+12,19.0,Fog.,29.0,1002.0,84,2024-07-15,7,15,2024,Monday,18:00,00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1063,"Saturday 30 January 2010, 18.00 — 00.00",1.264874e+12,10.0,Passing clouds.,26.0,1016.0,76,2010-01-30,1,30,2010,Saturday,18:00,00:00
1064,"Sunday 31 January 2010, 00.00 — 06.00",1.264896e+12,0.0,Clear.,23.0,1015.0,91,2010-01-31,1,31,2010,Sunday,00:00,06:00
1065,"Sunday 31 January 2010, 06.00 — 12.00",1.264918e+12,7.0,Haze.,29.0,1017.0,75,2010-01-31,1,31,2010,Sunday,06:00,12:00
1066,"Sunday 31 January 2010, 12.00 — 18.00",1.264939e+12,16.0,Passing clouds.,29.0,1014.0,55,2010-01-31,1,31,2010,Sunday,12:00,18:00
1067,"Sunday 31 January 2010, 18.00 — 00.00",1.264961e+12,7.0,Passing clouds.,26.0,1016.0,76,2010-01-31,1,31,2010,Sunday,18:00,00:00

In [116]:
days={'Monday':0, 'Tuesday':1,'Wednesday': 2, 'Thursday':3, 'Friday':4,'Saturday': 5, 'Sunday':6}
df['day_name']=df['day_name'].map(days)
df.head(2)

,date,date_id,wind,desc,temp,baro,hum,day,month,day_date,year,day_name,Start_hour,End_hour
0,"Sunday 14 July 2024, 18.00 — 00.00",1.720980e+12,9.0,Drizzle. Fog.,30.0,1003.0,82,2024-07-14,7,14,2024,6,18:00,00:00
1,"Monday 15 July 2024, 00.00 — 06.00",1.721002e+12,14.0,Fog.,29.0,1002.0,80,2024-07-15,7,15,2024,0,00:00,06:00

In [121]:
df.to_csv('Clean15Year.csv',index=False)